version: '3.9'
services:
  api:
    container_name: csv_uploader_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate &&
          gunicorn csv_uploader_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
     - .:/app